spring.application.name=api-gestao-vagas
management.metrics.tags.application=${spring.application.name}

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update

security.token.secret = ElFabrica@1234#
security.token.secret.candidate=ElFabrica@1234#Candidate

token.sonar=sqp_354026640f6580bdae9f5a1319be484daf13855b

management.endpoints.enabled-by-default=false
management.endpoints.web.exposure.include = health,metrics,prometheus
management.endpoint.health.enabled=true
management.endpoint.health.show-details=always
management.endpoint.metrics.enabled=true
management.endpoint.prometheus.enabled=true
