spring.application.name=demo

spring.datasource.url=jdbc:postgresql://localhost:5432/gestao_vagas
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update

security.token.secret = ElFabrica@1234#
security.token.secret.candidate=ElFabrica@1234#Candidate

token.sonar=sqp_354026640f6580bdae9f5a1319be484daf13855b

management.endpoints.enabled-by-default=false
management.endpoints.web.exposure.include = health,metrics,prometheus
management.endpoint.health.enabled=true
management.endpoint.show-details=always
management.endpoint.metrics.enabled=true
management.endpoint.prometheus.enabled=true