spring.application.name=api-gestao-vagas
management.metrics.tags.application=${spring.application.name}

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update

spring.data.mongodb.host=${MONGODB_HOST:localhost}
spring.data.mongodb.port=${MONGODB_PORT:27017}
spring.data.mongodb.database=${MONGODB_DATABASE:gestao_vagas_logs}
spring.data.mongodb.username=${MONGODB_USERNAME:mongo}
spring.data.mongodb.password=${MONGODB_PASSWORD:mongo}
spring.data.mongodb.authentication-database=${MONGODB_AUTHENTICATION_DATABASE:admin}
application.logs.http.enabled=${HTTP_ACCESS_LOGS_ENABLED:true}

security.token.secret = ElFabrica@1234#
security.token.secret.candidate=ElFabrica@1234#Candidate

token.sonar=sqp_354026640f6580bdae9f5a1319be484daf13855b

management.endpoints.enabled-by-default=false
management.endpoints.web.exposure.include = health,metrics,prometheus
management.endpoint.health.enabled=true
management.endpoint.health.show-details=always
management.endpoint.metrics.enabled=true
management.endpoint.prometheus.enabled=true
